### ISSUE TITLE
nvALT 2.2 crashes

### ISSUE THREAD

**Issue by Steinthal** [ttscoff/nv#374]
Downloaded the new version (both via the in-app update as well as via direct download):

Process:               nvALT [54844]
Path:                  /Applications/nvALT.app/Contents/MacOS/nvALT
Identifier:            net.elasticthreads.nv
Version:               2.2 (119)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nvALT [54844]
User ID:               502

Date/Time:             2016-09-23 01:35:29.737 +0200
OS Version:            Mac OS X 10.12.1 (16B2327e)
Report Version:        12

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/nvALT.app/Contents/MacOS/nvALT
  Reason: image not found

Binary Images:
       0x102730000 -        0x1027daff7 +net.elasticthreads.nv (2.2 - 119) <FB4F0D08-B234-368C-BB48-358D8B3437FF> /Applications/nvALT.app/Contents/MacOS/nvALT
       0x11102e000 -        0x11106b1c7  dyld (421.1) <590FD98B-4E55-3D9B-8450-41CA4C316D5F> /usr/lib/dyld
    0x7fffb404d000 -     0x7fffb404dfff  com.apple.Cocoa (6.11 - 22) <5EEB0A26-F1C2-3D57-8441-52C0B80C2A6A> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa

**Comment by adamjrice** [comment]
I'm getting the same error.

**Comment by guibarrette** [comment]
Same thing here and as mentioned on my email (thought I would post here seems it's seem to be the place to report bugs...). On my computer libcrypto is on "/usr/lib/libcrypto.dylib" and I have libcrypto.0.9.8.dylib, but I think libcrypto.dylib should be used for the linking

**Comment by ttscoff** [comment]
Yep. libcrypto isn't included in 10.12 so I had to make some modifications to compile there. I failed to statically link the new lib, so everyone who updated already is going to be unable to launch. My favorite kind of evening. I'll be putting out a new update in the morning, sincere apologies for the inconvenience.

**Comment by ttscoff** [comment]
Please see [here](https://github.com/ttscoff/nv/issues/380#issuecomment-249926381)

**Comment by guibarrette** [comment]
Hi Brett,

    thanks for the link!

Yes, I’ve experienced some crashes, but not as often as what others are
getting, but it seems related to the same thing as them. I’m giving you a
crash log if you want to have a look. But I just installed the debug
version you sent in the GitHub issue page. After a first look, it seems
fine. So, I’ll get back to you if I stumble on some crashes!

Thanks again,

   Guillaume




Activé 27 septembre 2016 à 12:54:03, Brett Terpstra (
notifications@github.com) a écrit:

Please see here
<https://github.com/ttscoff/nv/issues/380#issuecomment-249926381>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ttscoff/nv/issues/374#issuecomment-249926649>, or mute
the thread
